CREATE TABLE IF NOT EXISTS TESTTABLE(
   `nnnn` VARCHAR(255) NOT NULL
);

INSERT INTO TESTTABLE(`nnnn`) VALUES('12345');

CREATE TABLE IF NOT EXISTS EMPLOYEE(
   `name` VARCHAR(255),
   `email` VARCHAR(255),
   `personal_code` VARCHAR(255) NOT NULL,
   `tax_category` VARCHAR(255)
);
